export class Linecfg {
    line_no:string;
    session_id:string;
    cgwsvr_id:string;
    svc_nm:string;
    ap_id_cd:string;
    ap_sid:string;
    line_tp:string;
    line_st:string;
    log_switch_in:string;
    host_id:string;
    local_ip_addr:string;
    local_port_no:string;
    remote_ip_addr:string;
    remote_port_no:string;
    max_tps:string;
    comm_snd_buf_size:string;
    sync_in:string;
    oper_in:string;
    event_id:string;
    rec_id:string;
    rec_upd_usr_id:string;
    rec_upd_ts:string;
    rec_crt_ts:string;
  }