export class Subinfo {
    task_index:string;
    data_index:string;
    sub_id_cd:string;
    group_id:string;
    sub_seq:string;
    sub_conum:string;
    consist_in:string;
    fall_in:string;
    conv_in:string;
    conv_id:string;
    filter_in:string;
    filter_id:string;
    zip_in:string;
    enc_in:string;
    data_enc_md:string;
    data_enc_key:string;
    rec_len:string;
    bat_num:string;
    to_tm:string;
    resv_fld:string;
    task_desc:string;
    oper_in:string;
    event_id:string;
    rec_id:string;
    rec_upd_usr_id:string;
    rec_upd_ts:string;
    rec_crt_ts:string;
  }